//! Native integration tests for diagram-wasm.
//!
//! These tests run with `cargo test --workspace` (native rlib) and do NOT
//! require `wasm32-unknown-unknown`.
//!
//! ## JsValue constraint
//!
//! Functions returning `Result<T, JsValue>` must create a `JsValue` on the
//! error path. `wasm-bindgen`'s `JsValue` is only implemented for wasm32
//! targets; on native, creating a `JsValue` (e.g., via `JsValue::from_str`)
//! panics. Therefore:
//!   - Happy-path tests (functions returning `Ok`) work on native ✓
//!   - Error-path tests (expecting `Err`) require wasm32 — marked
//!     `#[cfg(target_arch = "wasm32")]`
//!
//! ## Test isolation
//!
//! Tests share the process-global `ENGINES` pool (`LazyLock`). Each test
//! creates and disposes its own engine via `with_engine()` to avoid leakage.

use diagram_core::PageId;

use diagram_wasm::{
    create_engine, dispose_engine, engine_can_redo, engine_can_undo, execute_command, get_scene,
    import_drawio, redo, render_pages, render_svg, undo,
};

/// Helper: create a temporary engine, run f, then dispose it.
/// This prevents pool leakage between tests.
fn with_engine<F, R>(f: F) -> R
where
    F: FnOnce(u32) -> R,
{
    let handle = create_engine().expect("create_engine should succeed");
    let result = f(handle);
    dispose_engine(handle).expect("dispose_engine should succeed");
    result
}

/// Build an AddPage command JSON using serde_json::json! macro.
/// The page ID is generated by the engine on apply.
fn cmd_add_page() -> String {
    let cmd = serde_json::json!({
        "AddPage": {
            "page": {
                "id": PageId::default(),
                "name": null,
                "size": {"width": 800.0, "height": 600.0}
            }
        }
    });
    serde_json::to_string(&cmd).unwrap()
}

/// Build an AddVertex command JSON. The vertex is placed on the given page_id.
fn cmd_add_vertex(page_id: PageId, label: &str, x: f64, y: f64, w: f64, h: f64) -> String {
    let cmd = serde_json::json!({
        "AddVertex": {
            "vertex": {
                "geometry": {"x": x, "y": y, "width": w, "height": h, "relative": false},
                "label": {"text": label},
                "page_id": page_id,
                "parent": null,
                "style_id": null
            }
        }
    });
    serde_json::to_string(&cmd).unwrap()
}

/// Reconstruct a PageId from scene JSON's {"idx": u64, "version": u32} representation.
fn page_id_from_scene_value(v: &serde_json::Value) -> PageId {
    serde_json::from_value(v["page_id"].clone()).expect("page_id should deserialize to PageId")
}

// ─── Engine lifecycle ─────────────────────────────────────────────────────────

#[test]
fn create_engine_returns_valid_handle() {
    let handle = create_engine().expect("create_engine should succeed");
    // handle is a u32 slotmap key; dispose succeeds = valid handle
    dispose_engine(handle).expect("dispose_engine should succeed");
}

#[test]
fn dispose_engine_is_idempotent() {
    let h = create_engine().expect("create_engine should succeed");
    dispose_engine(h).expect("first dispose should succeed");
    dispose_engine(h).expect("second dispose should succeed"); // idempotent
}

// ─── Command execution ────────────────────────────────────────────────────────

#[test]
fn execute_command_add_page_then_vertex() {
    with_engine(|handle| {
        let page_cmd = cmd_add_page();
        execute_command(handle, &page_cmd).expect("add page should succeed");

        // Get the actual page_id from the scene
        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let page_id = page_id_from_scene_value(&scene["pages"][0]);

        let vertex_cmd = cmd_add_vertex(page_id, "Node A", 10.0, 20.0, 100.0, 50.0);
        execute_command(handle, &vertex_cmd).expect("add vertex should succeed");

        // Verify scene has the page with display elements
        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let pages = scene["pages"].as_array().expect("pages should be array");
        assert_eq!(pages.len(), 1, "should have 1 page");
    });
}

// ─── Undo / Redo ─────────────────────────────────────────────────────────────

#[test]
fn undo_after_add_vertex_restores_empty_model() {
    with_engine(|handle| {
        let page_cmd = cmd_add_page();
        execute_command(handle, &page_cmd).expect("add page should succeed");

        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let page_id = page_id_from_scene_value(&scene["pages"][0]);

        let vertex_cmd = cmd_add_vertex(page_id, "Node A", 10.0, 20.0, 100.0, 50.0);
        execute_command(handle, &vertex_cmd).expect("add vertex should succeed");

        assert!(
            engine_can_undo(handle).expect("can_undo should succeed"),
            "can_undo should be true after adding"
        );

        undo(handle).expect("undo should succeed");

        assert!(
            engine_can_undo(handle).expect("can_undo should succeed"),
            "can_undo should be true after undo (page command still in history)"
        );
        assert!(
            engine_can_redo(handle).expect("can_redo should succeed"),
            "can_redo should be true after undo"
        );
    });
}

#[test]
fn redo_after_undo_reapplies_command() {
    with_engine(|handle| {
        let page_cmd = cmd_add_page();
        execute_command(handle, &page_cmd).expect("add page should succeed");

        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let page_id = page_id_from_scene_value(&scene["pages"][0]);

        let vertex_cmd = cmd_add_vertex(page_id, "Node A", 10.0, 20.0, 100.0, 50.0);
        execute_command(handle, &vertex_cmd).expect("add vertex should succeed");

        undo(handle).expect("undo should succeed");
        redo(handle).expect("redo should succeed");

        assert!(
            engine_can_undo(handle).expect("can_undo should succeed"),
            "can_undo should be true after redo (both commands still in history)"
        );
    });
}

#[test]
fn undo_with_empty_history_is_noop() {
    with_engine(|handle| {
        assert!(
            !engine_can_undo(handle).expect("can_undo should succeed"),
            "can_undo should be false on fresh engine"
        );
        undo(handle).expect("undo on empty history should be no-op");
        assert!(
            !engine_can_undo(handle).expect("can_undo should succeed"),
            "can_undo should still be false"
        );
    });
}

#[test]
fn new_command_clears_redo_history() {
    with_engine(|handle| {
        let page_cmd = cmd_add_page();
        execute_command(handle, &page_cmd).expect("add page should succeed");

        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let page_id = page_id_from_scene_value(&scene["pages"][0]);

        let v1 = cmd_add_vertex(page_id, "Node A", 10.0, 20.0, 100.0, 50.0);
        execute_command(handle, &v1).expect("add vertex 1 should succeed");

        undo(handle).expect("undo should succeed");
        assert!(
            engine_can_redo(handle).expect("can_redo should succeed"),
            "can_redo should be true after undo"
        );

        let v2 = cmd_add_vertex(page_id, "Node B", 30.0, 40.0, 80.0, 30.0);
        execute_command(handle, &v2).expect("add second vertex should succeed");

        assert!(
            !engine_can_redo(handle).expect("can_redo should succeed"),
            "can_redo should be false after new command"
        );
    });
}

// ─── Scene ───────────────────────────────────────────────────────────────────

#[test]
fn get_scene_on_empty_model_returns_empty_pages() {
    with_engine(|handle| {
        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let pages = scene["pages"].as_array().expect("pages should be array");
        assert!(pages.is_empty(), "empty model should have no pages");
    });
}

#[test]
fn get_scene_after_add_page_has_one_page() {
    with_engine(|handle| {
        let page_cmd = cmd_add_page();
        execute_command(handle, &page_cmd).expect("add page should succeed");

        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let pages = scene["pages"].as_array().expect("pages should be array");
        assert_eq!(pages.len(), 1, "should have exactly 1 page");
    });
}

// ─── Render ───────────────────────────────────────────────────────────────────

#[test]
fn render_svg_contains_label_text() {
    with_engine(|handle| {
        let page_cmd = cmd_add_page();
        execute_command(handle, &page_cmd).expect("add page should succeed");

        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let page_id = page_id_from_scene_value(&scene["pages"][0]);
        let vertex_cmd = cmd_add_vertex(page_id, "Node A", 10.0, 20.0, 100.0, 50.0);
        execute_command(handle, &vertex_cmd).expect("add vertex should succeed");

        // Serialize PageId using its serde impl (produces {"idx":..., "version":...})
        let page_id_json = serde_json::to_string(&page_id).unwrap();
        let svg = render_svg(handle, &page_id_json).expect("render_svg should succeed");
        assert!(
            svg.contains("Node A"),
            "SVG should contain label text 'Node A': {}",
            svg
        );
    });
}

#[test]
fn render_pages_returns_array_with_svg() {
    with_engine(|handle| {
        let page_cmd = cmd_add_page();
        execute_command(handle, &page_cmd).expect("add page should succeed");

        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let page_id = page_id_from_scene_value(&scene["pages"][0]);

        let vertex_cmd = cmd_add_vertex(page_id, "Node A", 10.0, 20.0, 100.0, 50.0);
        execute_command(handle, &vertex_cmd).expect("add vertex should succeed");

        let pages_json = render_pages(handle).expect("render_pages should succeed");
        let pages: Vec<serde_json::Value> =
            serde_json::from_str(&pages_json).expect("render_pages should return valid JSON array");

        assert_eq!(pages.len(), 1, "should have 1 page");
        assert!(
            pages[0].get("page_id").is_some(),
            "page should have page_id field"
        );
        assert!(pages[0].get("svg").is_some(), "page should have svg field");
        let svg = pages[0]["svg"].as_str().unwrap();
        assert!(svg.contains("<svg"), "svg should be an SVG string: {}", svg);
    });
}

// ─── Import ───────────────────────────────────────────────────────────────────

#[test]
fn import_drawio_replaces_model_atomically() {
    with_engine(|handle| {
        // Pre-populate with commands
        let page_cmd = cmd_add_page();
        execute_command(handle, &page_cmd).expect("add page should succeed");

        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let page_id = page_id_from_scene_value(&scene["pages"][0]);

        let v1 = cmd_add_vertex(page_id, "Pre-existing", 0.0, 0.0, 50.0, 50.0);
        execute_command(handle, &v1).expect("add vertex 1 should succeed");

        // Import simple-rect fixture
        let xml = include_str!("../fixtures/simple-rect.drawio");
        import_drawio(handle, xml).expect("import_drawio should succeed");

        // Scene should reflect imported model only
        let scene_json = get_scene(handle).expect("get_scene should succeed");
        let scene: serde_json::Value =
            serde_json::from_str(&scene_json).expect("scene should be valid JSON");
        let pages = scene["pages"].as_array().expect("pages should be array");
        assert_eq!(pages.len(), 1, "simple-rect should have 1 page");

        // Check display_list doesn't contain "Pre-existing" text
        let display_list = &pages[0]["display_list"];
        let arr = display_list
            .as_array()
            .expect("display_list should be array");
        for elem in arr {
            if let Some(text) = elem["text"].as_str() {
                assert!(
                    !text.contains("Pre-existing"),
                    "imported scene should not contain pre-existing vertices, found: {text}"
                );
            }
        }
    });
}

#[test]
fn import_drawio_resets_history() {
    with_engine(|handle| {
        let page_cmd = cmd_add_page();
        execute_command(handle, &page_cmd).expect("add page should succeed");

        assert!(
            engine_can_undo(handle).expect("can_undo should succeed"),
            "can_undo should be true after command"
        );

        let xml = include_str!("../fixtures/simple-rect.drawio");
        import_drawio(handle, xml).expect("import_drawio should succeed");

        assert!(
            !engine_can_undo(handle).expect("can_undo should succeed"),
            "can_undo should be false after import"
        );
        assert!(
            !engine_can_redo(handle).expect("can_redo should succeed"),
            "can_redo should be false after import"
        );
    });
}

// ─── wasm32-only tests ─────────────────────────────────────────────────────

/// JsValue::from_str is only available on wasm32; on native, the error path
/// (pool full) panics when trying to construct the JsValue error.
#[cfg(target_arch = "wasm32")]
#[test]
fn too_many_engines_returns_error() {
    let mut handles: Vec<u32> = Vec::with_capacity(64);
    for _ in 0..64 {
        let h = create_engine().expect("create_engine should succeed");
        handles.push(h);
    }
    let result = create_engine();
    assert!(result.is_err(), "65th engine should return error");
    for h in handles {
        dispose_engine(h).expect("dispose should succeed");
    }
}
